services:
  nowhere-snaps:
    env_file:
      - ./apps/snaps/.env
    container_name: nowhere-snaps
    build:
      context: .
      dockerfile: ./apps/snaps/Dockerfile
      target: runtime
    environment:
      - NODE_ENV=deployment

    ports:
      - "3000:3000"
    command: node apps/snaps/dist/apps/snaps/src/main.js

  nowhere-auth:
    container_name: nowhere-auth-dep
    env_file:
      - ./apps/auth/.env
    build:
      context: .
      dockerfile: ./apps/auth/Dockerfile
      target: runtime
    environment:
      - NODE_ENV=deployment

    command: node apps/auth/dist/apps/auth/src/main.js
    ports:
      - "3001:3001"
      - "50051:50051"

  nowhere-storage:
    env_file:
      - ./apps/storage/.env
    container_name: nowhere-storage-dep

    build:
      context: .
      dockerfile: ./apps/storage/Dockerfile
      target: runtime

    command: node apps/storage/dist/apps/storage/src/main.js
    ports:
      - "3002:3002"
      - "50052:50051"
  redis:
    image: redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data

volumes:
  redis_data:
