apiVersion: v1
kind: Service
metadata:
  name: nowhere-auth
spec:
  selector:
    app: nowhere-auth
  ports:
    - name: grpc
      protocol: TCP
      port: 50051
      targetPort: 50051
  type: ClusterIP
