apiVersion: v1
kind: Service
metadata:
  name: nowhere-snaps-cluster
spec:
  selector:
    app: nowhere-snaps
  ports:
    - name: grpc
      protocol: TCP
      port: 3000
      targetPort: 3000
  type: ClusterIP
