apiVersion: v1
kind: Service
metadata:
  name: nowhere-storage
spec:
  selector:
    app: nowhere-storage
  ports:
    - name: grpc
      protocol: TCP
      port: 50051
      targetPort: 50051
  type: ClusterIP
