apiVersion: v1
kind: Service
metadata:
  labels:
    app: nowhere-storage
  name: nowhere-storage-service
spec:
  type: NodePort
  ports:
    - name: 'nowhere-storage-service'
      port: 3002
      targetPort: 3002
      nodePort: 31002
  selector:
    app: nowhere-storage
